version: '3.8'
services:
  #nginx-lb:
  #  networks:
  #    - example
  #  build:
  #    context: .
  #    dockerfile: ./nginx/Dockerfile
  #  volumes:
  #    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #    - ./nginx/loadbalancer/include:/etc/nginx/include:ro
  #    - ./nginx/loadbalancer/conf.d:/etc/nginx/conf.d:ro
  #  depends_on:
  #    - application-1
  #    - application-2
  #  ports:
  #    - "80:80"
  
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass Abc123#
    volumes: 
      - cache:/data
  
  # application-1:
  #  container_name: app-1
  #  build:
  #    context: ./
  #    target: production
  #  image: quotes-api
  #  depends_on:
  #    - db
  #    - cache
  #  ports:
  #    - 3000:3000
  #  environment:
  #    NODE_ENV: production
  #    DB_HOST: db
  #    DB_PORT: 5432
  #    DB_USER: postgres
  #    DB_PASSWORD: postgres
  #    DB_NAME: postgres
  #    REDIS_HOST: cache
  #    REDIS_PORT: 6379
  #    REDIS_PASSWORD: Abc123#
  #  links:
  #    - db
  #    - cache
  #  volumes:
  #    - ./:/src
  
  # application-2:
  #  container-name: app-2

volumes:
  db:
    driver: local
  cache:
    driver: local